### PR TITLE
Improve clientside routing

### PR DESCRIPTION
**Pull request by simon04**
* Scroll to top after routing
* Use HashRouter to avoid 404 on deeplinks

### CODE REVIEW

**Comment by reiterbene** [comment]
instead of the HashRouter we could use an .htaccess file that redirects all 404 to our applications root (mod/rewrite), as the React-Application also handles 404s. But we should style the client-side 404 first.

**Comment by simon04** [comment]
I don't object keeping the `BrowserRouter`, I just went for the simpler solution. 😄
Adding a `.htaccess` brings in a dependency on the webserver to be used when deploying. Here's a possible configuration: http://readystate4.com/2012/05/17/nginx-and-apache-rewrite-to-support-html5-pushstate/

**Comment by reiterbene** [comment]
adding a .htaccess will require a rule in webpack to ship the file when running `npm run client:build`
your proposed .htaccess-file would suit our needs 👍

**Comment by simon04** [comment]
Alright. I added the `.htaccess` to the webpack build in 1a36dbc.

**Pull request merged**
